name: Hello World

on:
  push:
    branches:
      - test/pipeline
  pull_request:
    branches:
      - ZPS_2024_winter

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup singularity        
      uses: eWaterCycle/setup-singularity@v7

    - name: Print Hello World
      run: singularity --v
