name: Run Tests

on:
  push:
    branches:
      - test/pipeline
  pull_request:
    branches:
      - ZPS_2024_winter

jobs:
  run_tests_job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install gdown
      run: pip install gdown

    - name: Setup environment
      run:  |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libboost-all-dev \
            ccache

    - uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.3.4

    - name: Download file from Google Drive
      run: gdown ${{ secrets.CONTAINER_URL }}
    
    - name: Build and Test
      run: |
          # Run Singularity container
          singularity exec elitpc_tpcreco-sim-dev.sif bash -c '
            echo "Running inside Singularity container: $(hostname)"
            cat /proc/1/cgroup

            # Create a build directory and run the build
            mkdir build && cd build
            cmake -DBUILD_TEST=ON ../
            make install -j 4
          '
