name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-singularity:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Singularity
      run: |
        sudo apt-get update
        sudo apt-get install -y singularity-container

    - name: Download Singularity Image
      run: |
        wget -O app_container.sif ${{ secrets.SINGULARITY_IMAGE_URL }}

    - name: Run Singularity Image
      run: |
        singularity run app_container.sif
