name: Hello World

on:
  push:
    branches:
      - test/pipeline
  pull_request:
    branches:
      - ZPS_2024_winter

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.3.0
    - name: Run an apptainer container
      run: apptainer run docker://alpine cat /etc/os-release
