name: Hello World

on:
  push:
    branches:
      - test/pipeline
  pull_request:
    branches:
      - ZPS_2024_winter

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install gdown
      run: pip install gdown
        
    - name: Ensure repositories are up-to-date
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install -y \
        build-essential \
        libseccomp-dev \
        pkg-config \
        uidmap \
        squashfs-tools \
        fakeroot \
        cryptsetup \
        tzdata \
        dh-apparmor

    - name: Install Go
      run: sudo apt-get install -y golang-go

    - name: Clone Apptainer repository
      run: git clone https://github.com/apptainer/apptainer.git

    - name: Build Apptainer
      run: |
        cd apptainer
        ./mconfig
        cd $(/bin/pwd)/builddir
        make
        sudo make install
        cd ../..
  
    - uses: actions/checkout@v2

    - name: Download file from Google Drive
      run: gdown ${{ secrets.CONTAINER_URL }}
    
    - name: Build and Test
      run: |
          apptainer version
          singularity version
          singularity run elitpc_tpcreco-sim-dev.sif
          mkdir build
          cd build
          cmake -DBUILD_TEST=ON ../
