name: Hello World

on:
  push:
    branches:
      - test/pipeline
  pull_request:
    branches:
      - ZPS_2024_winter

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install gdown
      run: pip install gdown
    
    - uses: actions/checkout@v2
    
    - uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.3.0
    
    - name: Download file from Google Drive
      run: gdown ${{ secrets.CONTAINER_URL }}
    
    - name: List files
      run: ls -l
